devnames = [
  "WH-1000XM2 (AVRCP)",
  "Bose Mini II SE SoundLink (AVRCP)",
]

[commands]
PlayCD = "playerctl play-pause || playmusic -q &"
PauseCD = "playerctl play-pause || playmusic -q &"
NextSong = "playerctl next"
PreviousSong = "playerctl previous"
